apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: {{ include "wordpress-secure.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "wordpress-secure.imagePullSecret" . | b64enc }}