apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ include "wordpress-secure.namespace" . }}
  labels:
    {{- include "wordpress-secure.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ randAlphaNum 32 | quote }}
  mysql-password: {{ randAlphaNum 32 | quote }}
  mysql-database: {{ .Values.mysql.auth.database | default "wordpress" | quote }}