apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ include "wordpress-secure.namespace" . }}
  labels:
    {{- include "wordpress-secure.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
    {{- include "wordpress-secure.labels" . | nindent 4 }}
  clusterIP: None  # Headless service for direct pod access