{{- if .Values.phpmyadmin.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: phpmyadmin-network-policy
  namespace: {{ include "wordpress-secure.namespace" . }}
  labels:
    {{- include "wordpress-secure.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: phpmyadmin
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network-access: internal
    ports:
    - protocol: TCP
      port: 80
{{- end }}