apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: {{ include "wordpress-secure.namespace" . }}
  labels:
    {{- include "wordpress-secure.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "wordpress-secure.labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.wordpress.service.port }}
      targetPort: 80
  type: {{ .Values.wordpress.service.type }}