version: '3.8'

services:
  db:
    build: ./db
    image: project-root-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./wp-data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=password"]
      interval: 5s
      timeout: 10s
      retries: 10

  wp:
    build: ./wordpress
    image: project-root-wp
    depends_on:
      db:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "80:80"
    volumes:
      - ./wp-app:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini

  wpcli:
    build: ./wpcli
    image: project-root-wpcli
    volumes:
      - ./wp-app:/var/www/html
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      wp:
        condition: service_started
    links:
      - db

  pma:
    build: ./pma
    image: project-root-pma
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"

volumes:
  db_data: